version: "3"
services:
  web:
    build: apache
    ports:
    - 80:80
    - 433:433
    volumes:
    -./starwars:/app/starwars
    -./startrek:/app/starwars
    -./palpatine:/app/starwars
    -./apache/starwars.conf:/etc/apache2/sites-enabled/starwars.conf
    -./apache/startrek.conf:/etc/apache2/sites-enabled/startrek.conf